---

- name: dpkg | divert files
  command: dpkg-divert --local --divert '{{ item.diverted | default(item.original + divert_file_suffix) }}' --rename '{{ item.original }}'
  args:
    creates: '{{ item.diverted | default(item.original + divert_file_suffix) }}'
  when: (item.state|d('present') == 'present')
  with_items: divert_files_list_combined

- name: dpkg | Copy diverted configuration file to original location
  command: cp '{{ item.diverted | default(item.original + divert_file_suffix) }}' '{{ item.original }}'
  args:
    creates: '{{ item.original }}'
  when: (item.copy_to_org|d(False))
  with_items: divert_files_list_combined

- name: dpkg | remove file divert
  file:
    path: '{{ item.original }}'
    state: 'absent'
  when: (item.state|d('present') == 'absent' and (item.force|d() | bool))
  with_items: divert_files_list_combined

- name: dpkg | remove file divert
  command: dpkg-divert --rename --remove '{{ item.original }}'
  when: (item.state|d('present') == 'absent')
  with_items: divert_files_list_combined
